
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -79;
const int acc_off_y = -127;
const int acc_off_z = -230;
const float acc_scale_x = 9361.859532;
const float acc_scale_y = 9965.899358;
const float acc_scale_z = 9958.921094;

const int magn_off_x = -276;
const int magn_off_y = 270;
const int magn_off_z = -102;
const float magn_scale_x = 383.388747;
const float magn_scale_y = 419.015187;
const float magn_scale_z = 477.517047;
