
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 236;
const int acc_off_y = 260;
const int acc_off_z = -18;
const float acc_scale_x = 9351.964219;
const float acc_scale_y = 10082.972004;
const float acc_scale_z = 9915.252667;

const int magn_off_x = -672;
const int magn_off_y = -241;
const int magn_off_z = -514;
const float magn_scale_x = 376.433798;
const float magn_scale_y = 409.322561;
const float magn_scale_z = 475.686674;
